export const SET_LIBRARY = 'SET_LIBRARY';
export const UPDATE_COMIC = 'UPDATE_COMIC';
export const REMOVE_COMIC = 'REMOVE_COMIC';
export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';
export const ENQUEUE_TOAST = 'ENQUEUE_TOAST';
export const DISMISS_TOAST = 'DISMISS_TOAST';
export const SET_APP_VERSION = 'SET_APP_VERSION';

export const SET_VIEW = 'SET_VIEW';
export const OPEN_COMIC = 'OPEN_COMIC';
export const CLOSE_COMIC = 'CLOSE_COMIC';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_FIT_MODE = 'SET_FIT_MODE';
export const TOGGLE_THUMBNAILS = 'TOGGLE_THUMBNAILS';
export const SET_TOOLBAR_VISIBILITY = 'SET_TOOLBAR_VISIBILITY';
export const SET_READER_LOADING = 'SET_READER_LOADING';
